/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cryptogenerator;

import cryptogenerator.crypto.MakeTwentyFiveFilesInOneZip;

import java.io.IOException;

public class Main {
    public static void main(String[] args) throws IOException {
        MakeTwentyFiveFilesInOneZip createZip = new MakeTwentyFiveFilesInOneZip();
        createZip.createZip();
        //createZip.createZip(2);
    }
}

